spring.application.name=BaiTapLonJava_QLGV


#Kết nối với Database (MySQL_XAMPP)
spring.datasource.url = jdbc:mysql://localhost:3306/quanlygiaovien
spring.datasource.username = root
spring.datasource.password =

#JPA
#Tự động cập nhật bảng, tự tạo bảng column
spring.jpa.hibernate.ddl_auto = update
spring.jpa.show_sql = true

spring.thymeleaf.cache = false